### ISSUE TITLE
SECURITY.md

### ISSUE THREAD

**Issue by mike-audi** [tiki/.github#10]
Create a standard security.md file to be included in each repo

**Comment by timoguin** [comment]
GitHub now has private vulnerability reporting. The standard method involves a `SECURITY.md` with contact information for maintainers. This allows researchers to disclose and discuss any security issues privately with the maintainers.

With private vulnerability reporting, researchers can instead submit a private vulnerability report through the Security tab on a repository. It also gives them a one-click prompt for them to easily create a private fork of the repository (where they can work on a fix without disclosing it).

`SECURITY.md` should include an email contact for the security team (something like `security at mytiki dot com`), but we should lead them to the private vulnerability reports as our first preference.

https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability
