### ISSUE TITLE
Join Open Source Maintainers GitHub Org

### ISSUE THREAD

**Issue by timoguin** [tiki/.github#21]
## What?

> A place for open source maintainers on GitHub to collaborate with each other.

https://github.com/maintainers

This is a GitHub org for maintainers of open source projects. There are currently close to 350 members of the org.

## How?

They have an automated invitation process. Starring the [invite-automation](https://github.com/maintainers/invite-automation) repo will trigger an issue to be created for the user. From there, users comment on the issue to answer the basic questions about the name of the project, links to the repository, and why they want to join.

Here's a link to the issue that was create for me when I starred the repo: https://github.com/maintainers/invite-automation/issues/405

I see quite a number of `pending-invitation` issues in the repo, so the approval process is probably not fully automated. We may want to ping someone associated with the project.

**Comment by Fryguy** [comment]
FWIW, I opened an issue with not response: https://github.com/maintainers/invite-automation/issues/393 .  Not sure who to ping.

**Comment by timoguin** [comment]
> FWIW, I opened an issue with no response: https://github.com/maintainers/invite-automation/issues/393 .  Not sure who to ping.

Same. The automation seems broken. I haven't circled back around to try to contact anyone yet.

The email listed is opensource@github.com.

One of the repo owners is a developer advocate for GitHub named Rizel:

https://github.com/blackgirlbytes
https://blackgirlbytes.dev/
https://twitter.com/blackgirlbytes

**Comment by mike-audi** [comment]
closing, maybe they'll fix it one day.

**Comment by Fryguy** [comment]
They've created a new maintainers repo and invite process - checkout https://maintainers.github.com
