### ISSUE TITLE
Free 1Password Teams account for open source projects

### ISSUE THREAD

**Issue by timoguin** [tiki/.github#23]
## What?

1Password offers a team license for free to open source projects.

https://github.com/1Password/1password-teams-open-source

## How?

This is taken from the README in the repo referenced above.

### How to apply

~1. Create a team account: https://start.1password.com/signup/?t=B~
~2. Invite at least one other person to your team and [add them to the Owners group](https://support.1password.com/groups/#manage-group-membership).~
3. Fork this repo and add an entry to the `Open source projects using 1Password Teams` section at the bottom of this page:

```markdown
### Project name
A short description of what we do.
https://myawesomeproject.org
```

4. Create a pull request and fill out the template with the requested details.

**Comment by mike-audi** [comment]
it says the projects must be non-commercial so I'm not sure we qualify

**Comment by timoguin** [comment]
> it says the projects must be non-commercial so I'm not sure we qualify 

That... is a good point. 😆

**Comment by timoguin** [comment]
I'll look into it a bit more. They say to reach out to opensource@1password.com if you're unsure about qualifications.

**Comment by mike-audi** [comment]
Closing for now. We are commercial and the bill is only $20/m so most certainly not worth the effort at the moment.
