### ISSUE TITLE
Tailscale secure mesh network service

### ISSUE THREAD

**Issue by timoguin** [tiki/.github#24]
## What?

[Tailscale](https://tailscale.com/) is a wonderful VPN product that creates a transparent mesh network between nodes.

## Why?

Allow secure connectivity between staff devices (p2p) as well as any current or future private (cloud) networks or resources.

## How?

- Tailscale offers a license for free to open source projects (and families apparently?).
- Network ACLs and other security settings are fully configurable, e.g., only devs can access the dev private networks
- SSO is handled through GitHub, including mapping of GitHub teams to Tailscale teams.

## References

- About Tailscale ACLs: https://tailscale.com/kb/1018/acls/
- Tailscale Terraform provider: https://registry.terraform.io/providers/tailscale/tailscale/latest/docs
- Tailscale's breakdown of their relationship open source: https://tailscale.com/opensource/

**Comment by mike-audi** [comment]
Closing for now. Will reopen when ready to set up a TIKI VPN
