### ISSUE TITLE
Apply for Google Summer of Code

### ISSUE THREAD

**Issue by timoguin** [tiki/.github#27]
## What?

[Google Summer of Code](https://summerofcode.withgoogle.com/) is a yearly event where students and first-time OSS contributors are paid a stipend to work directly with open source organizations and projects. Mentors are paid a (smaller) stipend as well.

From their website:

> Google Summer of Code is a global, online program focused on bringing new contributors into open source software development. GSoC Contributors work with an open source organization on a 12+ week programming project under the guidance of mentors.

### Deadline for Applications

**NOTE**: ORGANIZATION APPLICATIONS WILL BE OPEN FROM ***JANUARY 23RD TO FEBRUARY 7TH***.

That gives us a few weeks to put a proposal together.

## Why?

Mentorship is about relationship building, visibility, and getting new contributors into our projects.

It's also, like, a kinda good and cool thing to do in general. YOLO.

## How?

- Gotta apply as an organization.
- The biggest part for the application is creating a projects page / idea list.

The actual work won't start until Summer 2023. Our projects and ideas should keep this in mind and attempt to reflect our future needs.

### References

| Article | Link |
| ------- | ---- |
| How GSoC works | https://google.github.io/gsocguides/student/how-gsoc-works |
| Mentor guide | https://google.github.io/gsocguides/mentor/ |
| Notes for first-year orgs | https://google.github.io/gsocguides/mentor/notes-for-first-year-organizations |
| Org application | https://google.github.io/gsocguides/mentor/org-application |
| Defining a project (ideas list) | https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list |

**Comment by mike-audi** [comment]
application window closed
