### ISSUE TITLE
Twitter Developer Program

### ISSUE THREAD

**Issue by timoguin** [tiki/.github#28]
## What?

Sign up for the Twitter Developer Program so we can create apps that monitor Twitter data and interact with the Twitter API in various ways.

## Why?

We can collect an analyze data about our own Twitter accounts, as well as those of select hashtags and keywords, with other types of filtering available.

We can also automate Tweet publishing via the API.

## How?

Sign up to be able to create apps. After that, investigate more.

### References

- https://developer.twitter.com/en
- https://developer.twitter.com/en/docs/tutorials/listen-for-important-events
- https://developer.twitter.com/en/docs/tutorials/getting-historical-tweets-using-the-full-archive-search-endpoint
- https://ossinsight.io/docs/workshop/twitter-insight

**Comment by mike-audi** [comment]
Closing: not a priority atm. 

Will reopen when we're ready to work on this.
