### ISSUE TITLE
Audit our GH actions policy

### ISSUE THREAD

**Issue by mike-audi** [tiki/.github#3]
check all our repos, to make sure all actions meet policy criteria before turning on.

**Comment by timoguin** [comment]
We can fork the repositories for any of the actions we use in the the Tiki GH org. This will ensure our actions will never change unexpectedly.

To make sure we don't miss out on upstream updates, the `sync` app that is installed in the GH org should keep each fork up-to-date. That app will force push to the main branch of the fork when upstream has new commits. If we want to ensure any extra layer of stability, we can create a separate `tiki` branch in each fork. After we review any changes in the main branch, we can merge it back.

**Comment by mike-audi** [comment]
Closing for now. Low priority. Will reopen at a later date.
