### ISSUE TITLE
Enable private vulnerability reporting for each repo

### ISSUE THREAD

**Issue by timoguin** [tiki/.github#32]
Private vulnerability reporting is a beta feature that allows researchers to disclose vulnerabilities privately to maintainers via the "Security" tab of the repository.

Currently, private vulnerability reporting needs to be enabled in the settings for each repo. This issue is to track that work.

https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability

Related to #10.

**Comment by mike-audi** [comment]
done.
