### ISSUE TITLE
We are going to simplify and deploy fast. 

### ISSUE THREAD

**Issue by mike-audi** [tiki/.github#62]
### Description

DISCUSSION PURPOSES ONLY.

Here's what I want us to do immediately. Now that we have a more or less functional system, we're going to prune, simplify, and focus on rapid development, testing, and deployment.

Changes to make immediately:

1) Consolidate everything that is not Lagoon in the spring boot service. Rename this service to API and archive all of the lambdas, rust, api gateway, etc. We will keep using Cognito for auth, but other than that the public API from tiki that will be used by the frontend should be served from the spring boot service. 
   - We need a great CI/CD pipeline with blue-green deployments
   - We need rock-solid unit tests
   - We need to add back the auto-generation of OAS3 docs from the endpoints
   - We need clear setup instructions on how to get started developing and testing locally
   - We need a way to test locally without cognito
   - We need to integrate the beehiv, attio, and lago apis with this service
2) Redo our aws org structure and get rid of org-formation. For now, there should just be: developer sandbox accounts, the prod workload account (account production, web production), the test workload account, all of the customer lagoon accounts, and shared (network, identity, etc.)
   - We need to set up control tower 
3) Refactor the lagoon project so we host a single dagster webserver, daemon, and code server and just execute the ecs tasks inside the customer lagoons. 
   - We need to write a customer grpc code server which loads code from s3 and hosts numerous code endpoints protected by api keys, which are passed into the ecs task exection
   - All compute should be orchestrated by dagster, for example we need to move the normalization code to a dagster job (still can call glue if we want)
   - We need to write an API facade layer which acts as the primary interface for all actions with the lagoon (both customer-hosted and tiki-hosted components)
   - We need to take all the plane code and make it a) so dagster/dbt code can be generated and tested locally, and b) be generated and deployed in the cloud without needing to build dagster images
   - We need to create a new cloudformation template for the customer-hosted portion, this should have a launch stack url
4) The dashboard project becomes the complete website. As in there is no tiki.company and dashboard.tiki.company. since the frontend marketing part of the website is also in Vue. Make this project be the whole thing at tiki.company. We can/should scrap the strapi stuff. We don't need it. Even the storefront stuff should get built right into this same web app and just use our apis to populate the required content. 
   

### Tasks

- [x] tiki/backend/issues/154

**Comment by ricardobrg** [comment]
Item 1 - tiki/backend/issues/153 and tiki/backend/issues/158 implemented the infrastructure for backend development. The  tiki/backend/issues/178 deliverable will publish it.
Item 2 - #63 is the deliverable to handle this. It is still in backlog, and will be implemented in the next weeks.
Item 3 - Under development.
Item 4 - tiki/frontend/issues/295 started the new website design. We are following up with tiki/frontend/issues/322 to publish it.
